### ISSUE TITLE
Post your screenshots here

### ISSUE THREAD

**Issue by rnkn** [rnkn/binder#1]
<img width="1283" alt="screenshot" src="https://user-images.githubusercontent.com/1256849/75653252-ec7b8300-5ca8-11ea-9d7d-af6a528abc2c.png">

**Comment by rnkn** [comment]
New screenshot

<img width="1482" alt="screenshot" src="https://user-images.githubusercontent.com/1256849/87218460-464a3300-c396-11ea-9ce7-30f7a5bc4377.png">

**Comment by rnkn** [comment]
Tutorial screenshot

<img width="1202" alt="screenshot" src="https://user-images.githubusercontent.com/1256849/93708258-1f6b6280-fb78-11ea-81d0-f2dc4397efc7.png">

**Comment by yibie** [comment]
Could it use with org-mode?

**Comment by rnkn** [comment]
@yibie each file can use whatever major mode you like.
