### ISSUE TITLE
Keybinding C-c ' on a global mode

### ISSUE THREAD

**Issue by oatmealm** [rnkn/binder#11]
This is not a bug, though this short cut is heavily used in `org-mode` to for `org-edit-special`... which when I started using initial caused a problem when `binder` was active. I've since re-mapped it.

**Comment by rnkn** [comment]
Yeah, Org does the wrong thing here, `C-c` + punctuation char is reserved for minor modes. Major modes are supposed to stick to `C-c C-<character>`.

According to `(info "(elisp) Major Mode Conventions")` even `C-c ;` and `C-c :` are for major modes, but this leaves precious few keys for much else...
