### ISSUE TITLE
Sidebar narrowing and widening by tags

### ISSUE THREAD

**Issue by oatmealm** [rnkn/binder#12]
After narrowing to a tag in the sidebar (`binder-sidebar-narrow-by-tag`) or excluding (`binder-sidebar-exclude-by-tag`), I couldn't see a way to cancel the narrowing and show all files in the active `binder` project... looking in `binder-siderbar-mode-map` I tried to "g" `binder-sidebar-refresh` which worked, but it's not obvious... maybe would be good to alias it to something recognizable?

**Comment by rnkn** [comment]
It's in the tutorial. Maybe I'll add a note to the docstrings on these commands.
