### ISSUE TITLE
Moving cursor back to side-bar

### ISSUE THREAD

**Issue by Arjay-El** [rnkn/binder#14]
Is there a keyboard shortcut for moving the cursor back out of the text frame to the sidebar? I am finding that I have to manually move the cursor back to the sidebar with my mouse once I have I have finished editing the text file. Did I miss a navigation feature or am I not using it correctly?
Thanks

**Comment by rnkn** [comment]
`C-c ;` - it's in the README, the code Commentary section, the tutorial, and the `C-h m` help...
