### ISSUE TITLE
On Windows, "Local variables entry is missing the suffix" error due to encoding utf-8-unix

### ISSUE THREAD

**Issue by nobiot** [rnkn/binder#5]
Hi @rnkn, 
Thank you for bringing Binder out to the world!

When I discovered it recently, I was instantly excited about the concept of Binder, and its simple aesthetics (and other Emacs packages of your creation -- I love Olivetti, too, and my personal theme emulates your theme style).

I was not sure if you were accepting PRs, so please take this as a humble suggestion.

I use Emacs on Windows (installed via [Scoop](https://scoop.sh/)).
I failed to configure Binder due to the "Local variables entry is missing the suffix" error. I use Doom Emacs, which uses its [Straight](https://github.com/raxod502/straight.el) as a "package management" system.

To cut the long story short, I have managed to get it to work by removing `coding utf-8-unix` local variable. Everything else went well.

I was not sure of the reasons why you needed it, so am happy for you to keep it as is. In that case, I'll use my modified version for now.

I have created a PR including the one-line change. I'll leave it up to you; merge it or keep the main branch as is.

Thank you again for creating something beautiful.
I'm trying to change my whole workflow, hoping to incorporate Binder as one of the main applications. 

Noboru Ota (nobiot)

**Comment by rnkn** [comment]
Thanks for the kind words.

Setting the file coding system is pretty core to Emacs, so I don't think this is an issue with binder. You've been able to visit the file, edit and write out to utf-8-unix encoding so I think this is an issue with the way straight loads packages (which I understand is quite complex).

Please attempt to reproduce this by launching Emacs with `emacs -Q` and then `M-x load-file RET [PATH TO binder.el]`

**Comment by nobiot** [comment]
Thanks, @rnkn. Will have a look. 
On a related note, Olivetti has `utf-8` (not `utf-8-unix`), and has no issue on my Windows.
I am suspecting that the `unix` bit might be the issue here (I had Flycheck giving me an error in `binder.el`).
I'll follow your suggestion and see the outcome. I'll let you know if I find out more.

**Comment by rnkn** [comment]
The `-unix` part is just to set line-endings when editing the source, which is of importance here because we're working across Windows/Unix systems.

I'm curious about whether this encoding is unavailable on Windows versions of Emacs, which will be my next step.

**Comment by nobiot** [comment]
I've recorded what I have done more carefully, following your advice.

Step 1. `load-file`
- emacs -Q and then M-x load-file RET [PATH TO binder.el]
- No issue. 
- You can use `binder-mode` and do `C-c '` to open the binder, etc.

Step 2. open `binder.el`
- emacs -Q, and then 'C-x C-f' to open `binder.el`
- You get  the "Local variables entry is missing the suffix" error.
- Despite the error, you can edit the file, save, etc.
![image](https://user-images.githubusercontent.com/12507865/79358834-0b289700-7f42-11ea-8f54-b6f69e78bee5.png)
- Note all the `^M` 's are carriage returns (via `describe-char`).
![image](https://user-images.githubusercontent.com/12507865/79359245-a6217100-7f42-11ea-91c2-04145fc7b702.png)

Step 3. `byte-compile-file`
- `M-x` `byte-compile-file` and select `binder.el`
- You get "binder.el:1443:18:Error: End of file during parsing" 
- No `.elc` file generated
![image](https://user-images.githubusercontent.com/12507865/79360260-f0572200-7f43-11ea-8a25-51d0d4f8912e.png)


Step 4. Use `utf-8` coding, instead of `utf-8-unix`
- All good with `.elc` file :)
- Note there is one warning message not related to the issue here
![image](https://user-images.githubusercontent.com/12507865/79359769-45deff00-7f43-11ea-9aba-3ad48df04f8b.png)

**Comment by rnkn** [comment]
Intriguing. Looks like you've narrowed it down quite well.

**Comment by nobiot** [comment]
If you are already going onto testing Windows, then you'd have picked it up too.  I would suggest to replace utf-8-unix with utf-8, rather than removing the local variable entirely...

**Comment by rnkn** [comment]
Yep I've merged your PR. Thanks!
