### ISSUE TITLE
Best way to install?

### ISSUE THREAD

**Issue by anthrolisp** [rnkn/binder#7]
What is the best way to install? Thank you very much!!

**Comment by rnkn** [comment]
Clone the repo somewhere and add this path to you `load-path` and then `(require 'binder)` in your init.
~~~elisp
(add-to-list 'load-path "~/code/binder")
(require 'binder)
~~~

**Comment by anthrolisp** [comment]
That works, it's installed. Commands are present and work manually M-x, but none of the keybindings work even when binder-enabled. Any thoughts?

**Comment by anthrolisp** [comment]
Or rather, C-c ; specifically is not working. Everything seems to.

**Comment by rnkn** [comment]
This is still alpha-level. It’s not really at bug-investigation state yet.
